<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [79]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.26.0
Pandas:  2.1.1
1.26.0


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [9]:
# wrong:
bikes = pd.read_table('/Users/vera/DS&AI/iod/DATA/bikeshare.csv', header=None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('/Users/vera/DS&AI/iod/DATA/bikeshare.csv', header=0)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('/Users/vera/DS&AI/iod/DATA/bikeshare.csv')
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
2  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
3  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...                                                                   
4  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...                             

ANSWER:

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [80]:
#ANSWER:
bikes=pd.read_table("/Users/vera/DS&AI/iod/DATA/bikeshare.csv")
print(bikes.head())

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
2  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
3  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...                                                                   
4  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...                                                                   


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be dealt with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [13]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [18]:
df = pd.read_excel('/Users/vera/DS&AI/iod/DATA/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For example, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [ ]:
#ANSWER


### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [19]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

time  latitude  longitude   depth  mag magType  nst  \
0  2023-12-07T06:38:50.337Z    8.8638   126.9023  52.766  5.2      mb   75   

   gap   dmin   rms  ...                   updated                  place  \
0   95  2.212  0.72  ...  2023-12-07T06:56:39.040Z  Mindanao, Philippines   

         type horizontalError depthError  magError  magNst    status  \
0  earthquake            3.82      6.795     0.043     178  reviewed   

   locationSource magSource  
0              us        us  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [21]:
url = 'https://www.ccra.com/airport-codes/'

df = pd.read_html(url)
df

[                City      Country Code
 0            Aalborg      Denmark  AAL
 1           Aalesund       Norway  AES
 2             Aarhus      Denmark  AAR
 3     Abbotsford, BC       Canada  YXX
 4     Abbotsford, BC       Canada  YXX
 ...              ...          ...  ...
 1574        Zanzibar     Tanzania  ZNZ
 1575        Zaragoza        Spain  ZAZ
 1576       Zhengzhou        China  CGO
 1577        Zhoushan        China  HSN
 1578          Zurich  Switzerland  ZRH
 
 [1579 rows x 3 columns]]

In [22]:
df[0]

City      Country Code
0            Aalborg      Denmark  AAL
1           Aalesund       Norway  AES
2             Aarhus      Denmark  AAR
3     Abbotsford, BC       Canada  YXX
4     Abbotsford, BC       Canada  YXX
...              ...          ...  ...
1574        Zanzibar     Tanzania  ZNZ
1575        Zaragoza        Spain  ZAZ
1576       Zhengzhou        China  CGO
1577        Zhoushan        China  HSN
1578          Zurich  Switzerland  ZRH

[1579 rows x 3 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here are a few examples: https://pandas.pydata.org/docs/user_guide/io.html#io-read-xml

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example:

In [23]:
url = 'https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

name language                id  \
0  Adeel Solangi   Sindhi  V59OF92YF627HFY0   
1  Afzal Ghaffar   Sindhi  ENTOCR13RSCLZ6KU   
2  Aamir Solangi   Sindhi  IAKPO3R4761JDRVG   
3  Abla Dilmurat   Uyghur  5ZVOEPMJUI4MB4EN   
4       Adil Eli   Uyghur  6VTI8X6LL0MMPJCC   

                                                 bio  version  
0  Donec lobortis eleifend condimentum. Cras dict...     6.10  
1  Aliquam sollicitudin ante ligula, eget malesua...     1.88  
2  Vestibulum pharetra libero et velit gravida eu...     7.27  
3  Donec lobortis eleifend condimentum. Morbi ac ...     2.53  
4  Vivamus id faucibus velit, id posuere leo. Mor...     6.49

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [24]:
#ANSWER
bikes.shape

(17379, 1)

What are the column names in `bikes`?

In [ ]:
#ANSWER


What are the data types of these columns?

In [25]:
#ANSWER
bikes.dtypes

instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt    object
dtype: object

What is the (row) index for this DataFrame?

In [ ]:
#ANSWER


https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this.
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [ ]:
#ANSWER


How would we use object notation to show the first 4 rows of `atemp`?

In [28]:
#ANSWER


SyntaxError: invalid syntax (2858134962.py, line 2)

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ):

In [ ]:
bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [ ]:
#ANSWER


What is the correct way to access the 2nd column of the DataFrame by its index?

In [ ]:
#ANSWER


## Handling Missing Values

What is the Pandas `isnull` function for?

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [29]:
bikes.isnull().head()

instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0                                              False                                                                    
1                                              False                                                                    
2                                              False                                                                    
3                                              False                                                                    
4                                              False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [33]:
#ANSWER
# bikes.isnull().sum()
bikes.isna().sum()

instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt    0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [ ]:
#ANSWER


What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER:

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [ ]:
#ANSWER
def divide(dividend, divisor):
    if divisor==0:
        quotient = np.nan
    else:
        quotient = dividend/divisor
    return (quotient)


Apply the Pandas `isna` function to the following data objects:

In [34]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [35]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [36]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [45]:
#ANSWER ????
bikes=pd.read_csv("../../DATA/bikeshare.csv")

How is the pandas I/O parameter `na_values` used?

? ANSWER:

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [42]:
#ANSWER


instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
2  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
3  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...                                                                   
4  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...

In [46]:
bikes.season.unique()

array([1, 2, 3, 4])

In [51]:
bikes["season"].value_counts()

season
3    4496
2    4409
1    4242
4    4232
Name: count, dtype: int64

In [50]:
bikes["season"].value_counts(normalize=True)

season
3    0.258703
2    0.253697
1    0.244088
4    0.243512
Name: proportion, dtype: float64

In [47]:
bikes.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5])

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns:

In [53]:
#ANSWER
bikes.describe().T

count         mean          std   min        25%        50%  \
instant     17379.0  8690.000000  5017.029500  1.00  4345.5000  8690.0000   
season      17379.0     2.501640     1.106918  1.00     2.0000     3.0000   
yr          17379.0     0.502561     0.500008  0.00     0.0000     1.0000   
mnth        17379.0     6.537775     3.438776  1.00     4.0000     7.0000   
hr          17379.0    11.546752     6.914405  0.00     6.0000    12.0000   
holiday     17379.0     0.028770     0.167165  0.00     0.0000     0.0000   
weekday     17379.0     3.003683     2.005771  0.00     1.0000     3.0000   
workingday  17379.0     0.682721     0.465431  0.00     0.0000     1.0000   
weathersit  17379.0     1.425283     0.639357  1.00     1.0000     1.0000   
temp        17379.0     0.496987     0.192556  0.02     0.3400     0.5000   
atemp       17379.0     0.475775     0.171850  0.00     0.3333     0.4848   
hum         17379.0     0.627229     0.192930  0.00     0.4800     0.6300   
windspeed   17379.0     0.190098     0.122340  0.00     0.1045     0.1940   
casual      17379.0    35.676218    49.305030  0.00     4.0000    17.0000   
registered  17379.0   153.786869   151.357286  0.00    34.0000   115.0000   
cnt         17379.0   189.463088   181.387599  1.00    40.0000   142.0000   

                   75%         max  
instant     13034.5000  17379.0000  
season          3.0000      4.0000  
yr              1.0000      1.0000  
mnth           10.0000     12.0000  
hr             18.0000     23.0000  
holiday         0.0000      1.0000  
weekday         5.0000      6.0000  
workingday      1.0000      1.0000  
weathersit      2.0000      4.0000  
temp            0.6600      1.0000  
atemp           0.6212      1.0000  
hum             0.7800      1.0000  
windspeed       0.2537      0.8507  
casual         48.0000    367.0000  
registered    220.0000    886.0000  
cnt           281.0000    977.0000

Compute and print the overall minimum and maximum of the numeric data columns:

In [58]:
bikes_min, bikes_max = (min(bikes.min(numeric_only=True)), max(bikes.max(numeric_only=True)))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [59]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code:

In [61]:
#ANSWER
bikes['atemp'].quantile([0.1, 0.25, 0.5, 0.75, 0.9])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [62]:
type(bikes['atemp'])

pandas.core.series.Series

In [63]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
8633      8634  2011-12-31       1   0    12  12        0        6   
8921      8922  2012-01-12       1   1     1  14        0        4   
16492    16493  2012-11-24       4   1    11  22        0        6   
14138    14139  2012-08-17       3   1     8   7        0        5   
8726      8727  2012-01-04       1   1     1  10        0        3   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
8633            0           1  0.52  0.5000  0.39     0.2985      93   
8921            1           1  0.42  0.4242  0.77     0.1642      24   
16492           0           1  0.24  0.2273  0.44     0.2537       7   
14138           1           1  0.64  0.2424  0.73     0.1045      11   
8726            1           1  0.06  0.1061  0.45     0.0000       7   

       registered  cnt  
8633          180  273  
8921          132  156  
16492          69   76  
14138         368  379  
8726           57   64

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indicates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [76]:
#feature engineering
bikes['atemp_labels'] = pd.cut(bikes['atemp'], bins = [0, 0.2, 0.4, 0.6, 0.8, 1], labels=['cold', 'mild', 'warm', 'hot', 'extreme'])
bikes.sample(10)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
10680    10681  2012-03-26       2   1     3   3        0        1   
11533    11534  2012-04-30       2   1     4  18        0        1   
5            6  2011-01-01       1   0     1   5        0        6   
1006      1007  2011-02-14       1   0     2  14        0        1   
14949    14950  2012-09-20       3   1     9   2        0        4   
1099      1100  2011-02-18       1   0     2  13        0        5   
6894      6895  2011-10-19       4   0    10  21        0        3   
9421      9422  2012-02-02       1   1     2  11        0        4   
8116      8117  2011-12-09       4   0    12  20        0        5   
10987    10988  2012-04-07       2   1     4  23        0        6   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
10680           1           1  0.46  0.4545  0.82     0.1940       0   
11533           1           2  0.56  0.5303  0.60     0.2239      53   
5               0           2  0.24  0.2576  0.75     0.0896       0   
1006            1           1  0.60  0.5909  0.15     0.4925      14   
14949           1           1  0.46  0.4545  0.72     0.0896       2   
1099            1           1  0.60  0.6212  0.43     0.1940      45   
6894            1           2  0.58  0.5455  0.94     0.1343       6   
9421            1           3  0.40  0.4091  0.82     0.2537       6   
8116            1           1  0.30  0.3333  0.81     0.0000      10   
10987           0           1  0.46  0.4545  0.23     0.2239      32   

       registered  cnt atemp_labels  
10680           1    1         warm  
11533         611  664         warm  
5               1    1         mild  
1006           76   90         warm  
14949           9   11         warm  
1099          131  176          hot  
6894           79   85         warm  
9421           99  105         warm  
8116          140  150         mild  
10987          86  118         warm

In [73]:
bikes.atemp.describe()

count    17379.000000
mean         0.475775
std          0.171850
min          0.000000
25%          0.333300
50%          0.484800
75%          0.621200
max          1.000000
Name: atemp, dtype: float64

What is `atemp_level`?

In [ ]:
#ANSWER


Here is a random sample of `atemp_level`:

In [ ]:
atemp_level.sample(5)

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [ ]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [ ]:
?????
bikes.drop([], axis=1)
import seaborn as sns
sns.heatmap(new_df.corr())
bike.corr()["windspeed"].sort_values()

In [ ]:
#ANSWER


*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initialise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [78]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )
a, b, c, d, e, 

(array([0., 0., 0.]),
 array([[1., 1., 1.]]),
 array([[[2, 8, 3, 9],
         [7, 5, 1, 3],
         [9, 7, 1, 3]],
 
        [[3, 6, 6, 2],
         [3, 8, 1, 2],
         [3, 9, 1, 4]]]),
 array([0, 1, 2, 3]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

## Load Data

Load rock.csv and clean the dataset.

In [ ]:
# ANSWER

## Check Column Names

Check column names and clean.

In [ ]:
# ANSWER

## Replace Null Values With 0

Check 'release_year' column whether this column has any null values or not. Replace null values with 0.

In [ ]:
# ANSWER

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column.

In [ ]:
# ANSWER

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [ ]:
# ANSWER

## Write Some Functions

### Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [ ]:
# ANSWER

### Write a function that converts a column in a DataFrame to a numeric type and otherwise replaces entries with np.nan

In [ ]:
# ANSWER

### Apply this last function to your dataset

In [ ]:
# ANSWER

### 'Describe' the new DataFrame

In [ ]:
# ANSWER

>




---



---



> > > > > > > > > © 2023 Institute of Data


---



---



