<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [1]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [2]:
# Read CSV
house_csv = "../../DATA/Sacramento_transactions.csv"
house = pd.read_csv(house_csv)
house.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [ ]:
# ANSWER 
# Price is the target variable, because Price is the variable that we need to predict in this context. 

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [3]:
# ANSWER
price_var = house[['beds', 'baths', 'sq__ft', 'latitude', 'longitude']]
price_var

beds  baths  sq__ft   latitude   longitude
0       2      1     836  38.631913 -121.434879
1       3      1    1167  38.478902 -121.431028
2       2      1     796  38.618305 -121.443839
3       2      1     852  38.616835 -121.439146
4       2      1     797  38.519470 -121.435768
..    ...    ...     ...        ...         ...
980     4      3    2280  38.457679 -121.359620
981     3      2    1477  38.499893 -121.458890
982     3      2    1216  38.708824 -121.256803
983     4      2    1685  38.417000 -121.397424
984     3      2    1362  38.655245 -121.075915

[985 rows x 5 columns]

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [12]:
# ANSWER 
# Beds, baths and sq__ft are the better predictors as the absolute correlationa and coefficience are higher than other. 
house.select_dtypes('number').corr()

zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [5]:
from sklearn.linear_model import LinearRegression

##### 2.4.1 Fit predictor and target variables using linear regression 

In [24]:
# ANSWER

X = house['sq__ft'].values.reshape(-1,1)
Y = house['price']
model = LinearRegression()
model.fit(X, Y)
coefficients = model.coef_
intercept = model.intercept_
print(coefficients, intercept)
print(Y[:5])

[54.15863969] 162930.16140699765
0    59222
1    68212
2    68880
3    69307
4    81900
Name: price, dtype: int64


##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [7]:
# ANSWER
r_square = model.score(X, Y)
r_square

0.11148717682951459

### 3. Splitting Data

In [8]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [19]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [23]:
# ANSWER
## Check training/test data
print(X_test.shape, y_test.shape, X_train.shape, y_train.shape)
print('X_test:',X_test[:5], 'y_test:', y_test[:5])
print(y_train)
print(y_train.shape)

(326, 1) (326,) (659, 1) (659,)
X_test: [[ 906]
 [2382]
 [1962]
 [1739]
 [1527]] y_test: 613     77000
451    236000
731    240971
436    221000
275    293993
Name: price, dtype: int64
433    217500
172     99000
125    335750
541    488750
879    104000
        ...  
106    280908
270    275000
860    610000
435    220000
102    265000
Name: price, Length: 659, dtype: int64
(659,)


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [28]:
# ANSWER
train_model = model.fit(X_train, y_train)
coefficients_t = model.coef_
intercept_t = model.intercept_

print(coefficients_t, intercept_t)

[47.43508406] 166482.34144968865


In [29]:
# ANSWER
test_rsquare = model.score(X_test, y_test)
test_rsquare

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [45]:
# ANSWER
predict_price_t = coefficients_t*1204 + intercept_t
predict_price_t

array([223594.18266381])

In [31]:
predict_price_t2 = model.predict([[1204]])
predict_price_t2

array([223594.18266381])

#### Find the error

In [32]:
# Predict price from X_test
model_test = model.fit(X_test, Y_test)
coefficients_tt = model.coef_
intercept_tt = model.intercept_
predict_price_tt = coefficients_tt*1204 + intercept_tt
print(coefficients_tt, intercept_tt, predict_price_tt)

[64.80336483] 159259.79264175825 [237283.04390223]


In [50]:
a = [[1204]]
model_test.predict(a)

array([237283.04390223])



---



---



> > > > > > > > > © 2023 Institute of Data


---



---



